apiVersion: v1
kind: Service
metadata:
  name: commonservices-linux-service
  namespace: commonservices-app
  labels:
    app: commonservices-linux-app
spec:
  type: LoadBalancer
  selector:
    app: commonservices-linux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080