apiVersion: apps/v1
kind: Deployment
metadata:
  name: commonservices-linux-deployment
  namespace: commonservices-app
  labels:
    app: commonservices-linux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commonservices-linux-app
  template:
    metadata:
      labels:
        app: commonservices-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: commonservices-container
          image: 588184019567.dkr.ecr.ap-southeast-1.amazonaws.com/commonservices:0.0.4
          ports:
            - name: http
              containerPort: 80
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: DB_NAME
            - name: KAFKA_BOOSTRAP_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: KAFKA_BOOSTRAP_SERVER_HOST
            - name: KAFKA_BOOSTRAP_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: KAFKA_BOOSTRAP_SERVER_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: DB_PASSWORD
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux